FROM docker.io/rocker/verse:devel
# Declare root as user 
# USER rstudio
# Update Ubuntu / Install Nanum for Korean Font
RUN    sudo sed -i 's/archive.ubuntu.com/mirror.kakao.com/g' /etc/apt/sources.list \
    && sudo sed -i 's/security.ubuntu.com/mirror.kakao.com/g' /etc/apt/sources.list \
    && sudo apt-get update \
    && sudo apt-get -y upgrade \
    && sudo apt-get install -y fonts-nanum* \  
    && sudo apt-get install -y fontconfig \
    && sudo fc-cache \
    && sudo rm -rf ~/.cache/matplotlib \
    && sudo chmod -R 777 /home/rstudio \
