version: '3'
#
services:
#    
    rstudio: 
        build:
          context: .
          dockerfile: ./dockerfiles/dockerfile-rstudio
        volumes: 
            - /mnt/e/github:/home/rstudio/github-anari
            - /mnt/e/rcache:/home/.cache
        ports: 
            - "8787:8787"
        environment: 
            - PASSWORD=1022
            - UMASK=000
            - ROOT=TRUE
            #- RENV_PATHS_CACHE=/home/anari/renv
        container_name: rstudio
# End of yml

# Command for wsl-ubuntu:
# docker-compose -f /mnt/e/github/setup-docker_compose/work-pc/wsl-podman-rocker.yml -p "anari-ds" up -d
#
# https://docs.docker.com/compose/reference/
# -f: file to to run docker 
# -p: name of project 
# up: up 
# -d: detached mode 