FROM rocker/verse:devel
# Declare root as user 
USER root
# Update Ubuntu / Install Nanum for Korean Font
RUN    sed -i 's/archive.ubuntu.com/mirror.kakao.com/g' /etc/apt/sources.list \
    && sed -i 's/security.ubuntu.com/mirror.kakao.com/g' /etc/apt/sources.list \
    && apt-get update \
    && apt-get -y upgrade \
    && apt-get install -y fonts-nanum* \  
    && apt-get install -y fontconfig \
    && sudo fc-cache -v \
    #&& sudo usermod -G root rstudio
    #&& sudo chown -R rstudio:rstudio /home/rstudio \ 
    && R -e "install.packages('renv')" \
    && R -e "install.packages('devtools')" \
    && R -e "Sys.setenv(R_INSTALL_STAGED = FALSE)"
