version: '3'
#
services:
#
    tf-gpu:
        image: tensorflow/tensorflow:latest-gpu-jupyter
        environment:
            - NVIDIA_DISABLE_REQUIRE=1
            - GRANT_SUDO=yes
            - JUPYTER_ENABLE_LAB=yes
            - JUPYTER_TOKEN=1022
        volumes:
            - "./data:/mnt/space/ml"
        ports:
            - "8889:8889"
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          device_ids: ['all']
                          capabilities: [gpu]
        container_name: tf_gpu
# End of yml

# Command: 
#  _ docker-compose -f /mnt/YOUR DIR/github/setup-docker_compose/5600H/docker-anari-tfgpu.yml -p "anari-tfgpu" up -d