version: '3'
#
services:
#
    tf-gpu:
        #image: tensorflow/tensorflow:latest-gpu-jupyter
        build:
          context: .
          dockerfile: ./dockerfiles/dockerfile-tfgpu
        privileged: true
        environment:
            - NVIDIA_DISABLE_REQUIRE=1
            - GRANT_SUDO=yes
            - JUPYTER_ENABLE_LAB=yes
            - JUPYTER_TOKEN=1022
        volumes:
            - /home/anari/tf-data:/tf/tf-data
            - /home/anari/github:/tf/github-anari
        ports:
            - 8889:8888
        # deploy:
        #     resources:
        #         reservations:
        #             devices:
        #                 - driver: nvidia
        #                   device_ids: ['all']
        #                   capabilities: [gpu]
        container_name: tf_gpu
# End of yml

# Command: 
#  _ docker-compose -f /home/anari/github/setup-docker_compose/5600H/ubuntu-podman-tfgpu.yml -p "anari-tfgpu" up -d
