version: '3'
#
services:
#    
    rstudio: 
        build:
          context: .
          dockerfile: ./dockerfiles/dockerfile-rstudio
        volumes: 
            - /mnt/c/Users/anari/github:/home/rstudio/github-anari
            - /mnt/c/Users/anari/renv:/home/rstudio/renv
        ports: 
            - "8787:8787"
        environment: 
            #- DISABLE_AUTH=true
            #- USER=anari
            - PASSWORD=1022
            - ROOT=TRUE 
            - RENV_PATHS_CACHE=/home/rstudio/renv
        container_name: rstudio
# End of yml

# Command for wsl-ubuntu:
# docker-compose -f /mnt/c/Users/anari/github/setup-docker_compose/5600H/wsl-podman-rocker.yml -p "anari-rocker" up -d
