version: '3'
#
services:
#    
    rstudio: 
        build:
          context: .
          dockerfile: ./dockerfiles/dockerfile-rstudio_wsl
        volumes: 
            - /mnt/c/Users/anari/github:/home/rstudio/github-anari
        ports: 
            - "8787:8787"
        environment: 
            #- DISABLE_AUTH=true
            #- USER=anari
            #- RENV_PATHS_ROOT=home/rstudio/renv
            #- RENV_PATHS_CACHE=/home/rstudio/renv-cache
            - PASSWORD=1022
            #- UMASK=000
            #- "R_INSTALL_STAGED=FALSE"
            - ROOT=TRUE 
        container_name: rstudio
# End of yml

# Command for wsl-ubuntu:
# docker-compose -f /mnt/c/Users/anari/github/setup-docker_compose/5600H/wsl_podman_rocker.yml -p "anari-rocker" up -d
